name: Validate Changed Recipes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AJV CLI
        run: npm install -g ajv-cli@5.0.0

      - name: Validate recipe files
        run: |
          recipe_files=$(find recipes/ -type f -name '*.json')
          
          if [ -z "$recipe_files" ]; then
            echo "No recipe files found to validate."
            exit 0
          fi
          
          for file in $recipe_files; do
            echo "Validating $file"
            ajv validate \
              --spec=draft2020 \
              -s schema/recipe.schema.json \
              -r schema/tags.flattened.json \
              -d "$file" || exit 1
          done
