name: Validate Changed Recipes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch base and head refs
        run: |
          git fetch origin main ${{ github.event.pull_request.head.ref }}

      - name: Check if any recipe files were modified
        id: check_changes
        run: |
          changed_files=$(git diff --name-only origin/main..origin/${{ github.event.pull_request.head.ref }} -- 'recipes/**/*.json' 'schema/recipe.schema.json')

          echo "Comparing origin/main to origin/${{ github.event.pull_request.head.ref }}"
          echo "Changed files:"
          echo "$changed_files"

          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$changed_files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          if [ -z "$changed_files" ]; then
            echo "No recipe-related changes found."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "Recipe-related changes detected."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Skip validation if no recipe files changed
        if: steps.check_changes.outputs.should_run == 'false'
        run: |
          echo "Skipping validation."
          exit 0

      - name: Set up Node.js
        if: steps.check_changes.outputs.should_run == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AJV CLI
        if: steps.check_changes.outputs.should_run == 'true'
        run: npm install -g ajv-cli@5.0.0

      - name: Validate changed recipe files
        if: steps.check_changes.outputs.should_run == 'true'
        run: |
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              ajv validate \
                --spec=draft2020 \
                -s schema/recipe.schema.json \
                -r schema/tags.flattened.json \
                -d "$file" || exit 1
            fi
          done
          exit 0